language: python
env:
  global:
    SEV_ARCHIVE = tests/testarchive.zip
python:
  - "2.7"
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"
script:
  - python slackviewer/main.py
  - python cli.py clean
  - python cli.py clean -w
  - python -m pytest tests
