version: "3"
services:

  uwsgi:
    build: ./
    volumes:
      - ./:/var/www/
    ports:
      - "3031:3031"
    environment:
      TZ: "Asia/Tokyo"
      SEV_ARCHIVE: "/var/www/slackviewer/archive.zip"

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - uwsgi
    ports:
      - "4231:80"
    environment:
      TZ: "Asia/Tokyo"